services:
  - type: web
    name: meme-coin-sniper
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        fromEnvVar: BOT_TOKEN
      - key: TELEGRAM_CHAT_ID
        fromEnvVar: TELEGRAM_CHAT_ID
      - key: HONEYPOT_API_KEY
        fromEnvVar: HONEYPOT_API_KEY
